update

diff --git a/dnsmasq-extra/files/sh/init b/dnsmasq-extra/files/sh/init
--- a/dnsmasq-extra/files/sh/init
+++ b/dnsmasq-extra/files/sh/init
@@ -105,6 +105,7 @@ EOF
 EOF
 	fi
 
+	echo -n "ABDLOCK, " && ( sed "s/^/address=\//;s/$/\/${BLOCK}/" $IPSETDIR/adblock > $DNSMASQDIR/adblock.conf )
 	echo -n "CUSTOM" && ( echo "conf-file=$IPSETDIR/custom.conf" > $DNSMASQDIR/custom.conf )
 
 	echo "all-servers" > $DNSMASQDIR/alls.conf
@@ -126,6 +127,7 @@ clean_dir() {
 	rm -rf $DNSMASQDIR/dnscpt.conf    2>/dev/null
 	rm -rf $DNSMASQDIR/ssdns.conf     2>/dev/null
 	rm -rf $DNSMASQDIR/ssrdns.conf    2>/dev/null
+	rm -rf $DNSMASQDIR/adblock.conf   2>/dev/null
 	rm -rf $DNSMASQDIR/gfwlist.conf   2>/dev/null
 	rm -rf $DNSMASQDIR/direct.conf    2>/dev/null
 	rm -rf $DNSMASQDIR/koolproxy.conf 2>/dev/null
@@ -151,7 +153,8 @@ restart() {
 update(){
 	update_sub 'gfwlist'
 	update_sub 'direct'
-	update_sub 'koolproxy'
+#	update_sub 'koolproxy'
+#	update_chn
 }
 
 update_sub(){
@@ -179,6 +182,27 @@ update_sub(){
 	echo "# $file is broken, failsafe Now!"
 	rm -f "${file}"
 	cp -f "${bak}" "${file}" || cp -f "/rom${file}" "${file}"
+}
+
+update_chn(){
+	chnroute=/etc/dnsmasq-extra.d/chnroute.txt
+	[ "Z$chnroute" != "Z" ] || return 0
+
+	chnsrc='https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt'
+
+	echo "# $chnroute Updating"
+	curl --connect-timeout 10 --max-time 120 -ksSL $chnsrc -o $chnroute
+	if [ $? -eq 0 ]; then
+		echo "# $chnroute Updated"
+	else
+		echo "# $chnroute NOT Updated"
+	fi
+
+	if [ ! -f "$chnroute" ] || [ $(ls -l "$chnroute" | awk '{print $5}') -lt 4096 ]; then
+		echo "# $chnroute is broken, failsafe Now!"
+		rm -f "$chnroute"
+		cp -f "/rom$chnroute" "$chnroute"
+	fi
 }
 
 rules(){
